### ISSUE TITLE
Bean Migration Question

### ISSUE THREAD

**Issue by darbyjack** [AuthMe/ConfigMe#117]
Hi there,

I had a quick question and that was if it's possible to migrate bean properties as a whole. The only thing is, I don't want to migrate it to a different part of the config. I currently have a custom bean that contains an int and a string. I would like to (if possible) be able to change the string in the bean to a list of strings, and when run, it would read in that single old string and convert it to a single entry of list in the same spot of the config.

Thanks for your time.

**Comment by ljacqu** [comment]
Hi!

This should be possible by using the bean mapper to try and load the bean in its old form in the migration service. Subsequently, convert it to the new one. I can write up a prototype in 10-14 hours to make it more clear. :)

**Comment by darbyjack** [comment]
A prototype would be awesome! Thank you!

**Comment by ljacqu** [comment]
Alright, I tried out the second approach with the commit above and it works out quite well. It uses the following config property: https://github.com/AuthMe/ConfigMe/blob/master/src/test/resources/beanmapper/nested_chat_component.yml but you'll see in the commit that the bean property type it tests with has `color` as a list of strings.

I extended the bean mapper and made it wrap single values into a collection whenever a collection property is needed. It also registers an "error" which will trigger the config to be rewritten (keeping all the values) with the new structure, just remove that if it's undesired.

Note in the settings holder of the commit that the new specific bean mapper is passed into the property, otherwise it would still use the default one :) 

--- 

No prototype for the first approach as I don't think it would make sense in your case. What I meant is you'd keep the old class of your bean and try to map it to it in the migration service if the property doesn't have a value from the resource. Then if the mapping to the old version succeeded you could convert the old object to the new one and set it to the ConfigurationData. 

I'd personally favor this approach if you have complicated changes like renamings or type changes. But the mapper just accepts a little more values for collection properties, it's quite slim and easy to follow :)
