### ISSUE TITLE
Support for Map properties without beans

### ISSUE THREAD

**Issue by jamezrin** [AuthMe/ConfigMe#49]
Right now you cannot use a Map without relying on a bean class

**Comment by jaime29010** [comment]
This directly makes Lists values able to be serialized like beans, now you can only have String lists and If you want a list of something else you have to use a bean, adding another subpath to the configuration

**Comment by ljacqu** [comment]
Looks very good so far! Assuming your second comment is actually talking about Map's with String keys, right? :)

**Comment by jaime29010** [comment]
Yes, it is a little bit confusing what I tried to explain in that message, but what I meant is that for this issue to be able to be closed the leaf property generator has to support not only BeanProperty classes but also any Property that has a bean class as a type.
That would also make it so that you can create List properties not only for strings.
The bukkit configuration api supports boolean, byte, character, integer, long, map, short and string lists, I aim to do something like that.

I'm going on a trip so I will not be able to work on this until Monday, only if I were productive this afternoon... I will get to this and the other issues as soon as possible.

**Comment by ljacqu** [comment]
Thanks for the explanation. Take all the time you need! I'm available on Discord for chatting and otherwise won't be doing much on ConfigMe as I'm having a round of development on the injector. So no need to worry about any code conflicts etc. either.
Btw I love how you 100% matched the current code style, down to the newlines in the Javadoc and the usage of `@Nullable`. Quite impressive!

**Comment by jaime29010** [comment]
These commits are just me playing around, I don't know this codebase and I'm a bit lost, so yeah, expect something better not that.

**Comment by Jamezrin** [comment]
What is your opinion on that commit? I don't know if creating a bean property for the map is right or not.

**Comment by ljacqu** [comment]
Hi @Jamezrin , sorry for the late reply.

The code looks OK to me. I am in general not happy how the export is being handled—as ConfigMe grew bigger I never tended to that portion of the code so it's a mess. Part of the reason is I'm not really sure how it could be restructured better... I think we're doing too much (de)serialization by hand rather than relying on SnakeYAML.

For now I try to cover the bad code with as many tests as possible. If you could add some unit tests for `StringKeyMapProperty` that would be pretty cool.

**Comment by Jamezrin** [comment]
I have tried to, and while doing so I realized the way of importing the `StringKeyMapProperty` does not make any sense. 
This overwhelms me, I'm not that experienced, but I tried my best.
Thanks for being so nice.
Sorry, I will close the issues I've opened.

**Comment by ljacqu** [comment]
Considering the refactoring that is being done within 1.0 I'm taking the liberty of reopening this again. I think it should be easy to implement once 1.0 is out.
